### ISSUE TITLE
Python上でlogin画面でエラーが出ている

### ISSUE THREAD

**Issue by hsano333** [M1n01/ft_transcendence#136]
いつのまにかエラーが出ている
Internal Server Error: /ja/spa/nav
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2761, in to_python
    return uuid.UUID(**{input_form: value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/uuid.py", line 175, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

このエラーを追っていけば解決できそう。ひとまず後回し
  File "/workspace/backend/spa/views.py", line 29, in get
    list = UserNotification.objects.filter(Q(user=request.user) & Q(is_read=False))

**Comment by hsano333** [comment]
Naviバーにユーザー情報が必要なデータを取得しなければいけないが、ログインしていない状態だと取得できずに例外が発生するのが原因。try excpetで対応する。
Gameのトーナメント用のプルリクで修正予定

**Comment by hsano333** [comment]
#141 で対応済み
