### ISSUE TITLE
本番環境でトーナメント試合でエラーが発生した

### ISSUE THREAD

**Issue by hsano333** [M1n01/ft_transcendence#183]
トーナメントを開催して、最後の５点目を入れた瞬間にしばらくフリーズし、数秒後に勝利を表す画像が出た。その時のlogを見ると次のようなエラーが出ていた。
対応が必要

```
172.38.10.10:38168 - - [24/Oct/2024:15:21:04] "POST /ja/pong/add-score/36e82823-cc4b-4bed-bbb6-c719dcc4ac90" 200 78
[2024-10-24 15:21:13,017: ERROR/ForkPoolWorker-15] Task accounts.tasks.delete_tmp_user[d7179f39-afa2-4f6b-a092-049aea7160a9] raised unexpected: DoesNotExist('FtTmpUser matching query does not exist.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/backend/accounts/tasks.py", line 7, in delete_tmp_user
    user = FtTmpUser.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
accounts.models.FtTmpUser.DoesNotExist: FtTmpUser matching query does not exist.
```

**Comment by hsano333** [comment]
内容を見る限り、試合は関係ないかも
TmpUserを定期的に消しているが、それの削除に失敗している？

**Comment by hsano333** [comment]
よくよく考えてみると、試合終わった後に固まったのはブロックチェーンに保存するのが長かっただけのような気がする。
それはそうと、Python側のエラーハンドリングは必要なので、そちらは修正した
